### ISSUE TITLE
Describe uploading and downloading files

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix-v1-v2-docs#367]
I think we should create a dedicated section on uploading and downloading files in [Managing Files](https://docs.jmix.io/jmix/files/index.html), where we summarize all techniques and usage of FileUploadFields, Downloader, BrowserFrame, etc.

**Comment by knstvk** [comment]
I don't like what we got at the moment. Consider changing the section to the following structure:

- Managing Files
  - Storing Files in Database (keep as is)
  - Using File Storage (keep as is)
  - Uploading Files
    - UI Components (what UI components can be used to upload files and why? No duplicating examples, they already exist in UI components sections)
    - Using TemporaryStorage (see complete content below)
  - Downloading and Displaying Files
    - Using Downloader
      - Downloading from File Storage
      - Downloading Arbitrary Resources (byte arrays - from DB fields, local files; using `DownloadDataProvider`; using `ResourceDataProvider` if it makes sense)
      - Displaying Files in Web Browser
    - Using Image (when to use `Image` and what it can show)
    - Using BrowserFrame (when to use `BrowserFrame` and what it can show)


```
[[using-temporary-storage]]
=== Using TemporaryStorage

The `FileStorageUploadField` component has the xref:ui:vcl/components/file-storage-upload-field.adoc#file-storage-put-mode[fileStoragePutMode] attribute with the default value `IMMEDIATE`. If you set it to `MANUAL`, the component uploads the file to the temporary storage in the file system of the application, and gives you full control over the uploaded file: you can transfer the file to the file storage as is, pre-process it, or do whatever you need with the file without saving it to the file storage at all.

The same is true for the xref:ui:vcl/components/file-multi-upload-field.adoc[FileMultiUploadField] component: it just uploads files to the temporary storage and notifies your code that the upload is complete.

The `TemporaryStorage` interface provides an API to create temporary files, save them to the file storage, or remove them.

Below is an example of using `FileStorageUploadField` in manual mode transfer the uploaded file from temporary storage to the file storage.

[source,xml,indent=0]
----
<fileStorageUpload id="fileField"
                   property="image"
                   fileStoragePutMode="MANUAL"/> <!--1-->
----
<1>  Set `fileStoragePutMode="MANUAL"` for the upload field component

[source,java,indent=0]
----
@Autowired
private FileStorageUploadField fileField;
@Autowired
private TemporaryStorage temporaryStorage;

@Subscribe("fileField")
public void onFileFieldFileUploadSucceed(SingleFileUploadField.FileUploadSucceedEvent event) {
    File file = temporaryStorage.getFile(fileField.getFileId()); // <1>
    if (file != null) {
        FileRef fileRef = temporaryStorage.putFileIntoStorage(fileField.getFileId(), event.getFileName()); // <2>
        fileField.setValue(fileRef);
    }
}
----
<1> Get local file from the temporary storage using identifier provided by the upload field.
<2> Transfer local file to the file storage.

The `putFileIntoStorage()` method also removes the temporary local file.

If you only need to process the file locally without saving it to file storage, use the `deleteFile()` method of `TemporaryStorage` after working with the file, for example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/files/ex1/screen/files/FilesScreen.java[tags=get-and-delete]
----

The temporary storage tends to accumulate files that were not deleted for various reasons. So it provides a JMX interface for removing such old unused files. You can find it by *jmix.ui:type=TemporaryStorage* name in *Administration -> JMX Console* screen. The MBean has the `clearTempDirectory()` method that removes all files from the temporary directory of the application (`.jmix/temp` by default) which are older than 2 days. You can call this method manually, or use a xref:quartz:index.adoc[Quartz] job to do it periodically. In a job, you should inject the `TemporaryStorageManagementFacade` bean and call its `clearTempDirectory()` method.

```

**Comment by oshiryaeva** [comment]
@knstvk thus, should we remove this section completely?

[[file-storage-upload]]
== Uploading with FileStorage Interface

The following example shows how to work with the https://github.com/jmix-framework/jmix/blob/master/jmix-core/core/src/main/java/io/jmix/core/FileStorage.java[FileStorage^] interface directly. This interface is designed to store and load files defined by file references.

The first method saves a file obtained from a web service to the file storage. The same `Attachment` entity is used as in the <<ui-upload,previous example>>:

````
@Autowired
private FileStorageLocator fileStorageLocator; 
@Autowired
private DataManager dataManager;

private void getAndSaveImage() {
    try {
        
        URLConnection connection = new URL("https://picsum.photos/300").openConnection();
        try (InputStream responseStream = connection.getInputStream()) {
            
            FileStorage fileStorage = fileStorageLocator.getDefault();
            FileRef fileRef = fileStorage.saveStream("photo.jpg", responseStream);
            
            Attachment attachment = dataManager.create(Attachment.class);
            attachment.setFile(fileRef);
            dataManager.save(attachment);
        }
    } catch (IOException e) {
        throw new RuntimeException("Error getting image", e);
    }
}
````
<1> `FileStorageLocator` allows you to work with a particular file storage if you have defined xref:file-storage.adoc#multiple-fs[multiple file storages] in your project. If you have a single file storage (which is a default situation), you can inject the `FileStorage` interface directly.
<2> Getting an input stream for the web resource. Instead of the `URLConnection` class, you may want to use `HttpClient` introduced in Java 11, or a third-party library like Apache HttpClient.
<3> Saving the resource content to the file storage. The returned `FileRef` object is a reference to the file in the file storage.
<4> Saving the reference to an entity attribute.

The second method loads a file from the file storage and saves it to the local file system.

````
private void saveToLocalFile(Attachment attachment, Path path) {
    FileStorage fileStorage = fileStorageLocator.getDefault();
    FileRef fileRef = attachment.getFile();
    
    InputStream inputStream = fileStorage.openStream(fileRef);
    try {
        
        Files.copy(inputStream, path.resolve(fileRef.getFileName()),
                StandardCopyOption.REPLACE_EXISTING);
    } catch (IOException e) {
        throw new RuntimeException("Error saving image", e);
    }
}
````
<1> Getting an input stream to load the file from the file storage.
<2> Saving the file to the local file system.

TIP: Use `FileStorage` directly only for highly-available external services. In other cases, for the storage integrity it is preferable to use `TemporaryStorage`.

**Comment by knstvk** [comment]
@oshiryaeva - yes, it duplicates an example in Using File Storage. And it's not actually about uploading, it's about moving files to/from FileStorage.
