### ISSUE TITLE
Jmix version in the web page header

### ISSUE THREAD

**Issue by vfadeevGit** [jmix-framework/jmix-v1-v2-docs#607]
Problem: Customers signal that they get confused when searching across the documentation because they don't understand the version of platform in the search results options and don't understand how to switch to the version of Jmix they actually using. The UI component which allows to switch btw the Jmix versions is located in the left bottom side menu and based on the users' feedback can't be easily noticed.

Solution: Put the current Jmix platform version in the header of the documentation web page making the choice more explicit and easier for the users to allocate.

**Comment by vfadeevGit** [comment]
@knstvk please gain priority for this issue. Thanks!

**Comment by knstvk** [comment]
In the suggested design the full version is shown: "Version 2.0". We cannot duplicate all versions (2.0, 2.1, etc.) in the top selector, because they are generated automatically based on branches.

In fact there is only v1 / v2 choice: `https://docs.jmix.io/` or `https://docs.jmix.io/1.x/`, so the top selector should contain only the "major" number (1, 2, 3, ...). The question is, how it should read? 
Possible options:
- `Jmix Documentation | Version 1`
- `Jmix Documentation | Version 1.x`
- `Jmix Documentation | v.1`
- `Jmix Documentation | v.1.x`
What do you prefer? I would go for the first option.
